version: '3'
services:
  postgres:
    image: postgres:15
    container_name: spongebob_db
    environment:
      POSTGRES_USER: spongebob_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: spongebob_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
